#!/bin/bash
EMACS=${EMACS:-emacs}
${EMACS} -batch -L ${srcdir}/.. -L ${srcdir}/../../elfeed  -L ${srcdir}/../../elfeed/tests  -l ${srcdir}/elfeed-score-tests.el --eval '(progn (setq ert-batch-backtrace-right-margin 80) (ert-run-tests-batch-and-exit "^elfeed-score-test"))'
