#!/bin/bash
EMACS=${EMACS:-emacs}
${EMACS} -batch -L ${srcdir}/.. -l ${srcdir}/elfeed-score-tests.el --eval '(let ((ert-batch-backtrace-right-margin 120)) (ert-run-tests-batch-and-exit "^elfeed-score-test"))'
