#!/bin/bash
EMACS=${EMACS:-emacs}
${EMACS} -batch -L . -L ${srcdir}/.. -l ${srcdir}/test-serde.el --eval '(let ((ert-batch-backtrace-right-margin 120) (ert-batch-print-length 120) (ert-batch-print-level 25)) (ert-run-tests-batch-and-exit t))'
