#!/bin/bash
EMACS=${EMACS:-emacs}
${EMACS} -batch -L ${srcdir} -L ${srcdir}/..  -l ${srcdir}/test-udf-rules.el --eval '(progn (setq ert-batch-backtrace-right-margin 120) (ert-run-tests-batch-and-exit "^elfeed-score-test-udf-rules"))'
