#+TITLE: elfeed-score
#+DESCRIPTION: Gnus-style scoring for Elfeed
#+AUTHOR: Sp1ff
#+EMAIL: sp1ff@pobox.com
#+DATE: <2020-03-14 Sat 18:59>
#+AUTODATE: t
#+OPTIONS: toc:nil org-md-headline-style:setext *:t ^:nil

[[https://melpa.org/#/elfeed-score][file:https://melpa.org/packages/elfeed-score-badge.svg]]
[[https://stable.melpa.org/#/elfeed-score][file:https://stable.melpa.org/packages/elfeed-score-badge.svg]]

* Introduction

[[https://github.com/sp1ff/elfeed-score][elfeed-score]] brings Gnus-style [[https://www.gnu.org/software/emacs/manual/html_node/gnus/Scoring.html#Scoring][scoring]] to [[https://github.com/skeeto/elfeed][Elfeed]].

[[https://github.com/skeeto/elfeed][Elfeed]] is an extensible web feed reader for Emacs. By default, it will display entries in reverse chronological order. This package defines a bit of metadata for each of your feed entries: a "score". A score is an integer (negative or positive), and higher scores denote entries of greater interest to you. This package also installs a new sort function, so that Elfeed will display entries with higher scores before entries with lower scores (entries with the same scores will still be sorted in reverse chronological order).  It also provides an entry display function for the search buffer that displays each entry's score, should you choose to install it.

While you can manually assign a score to an entry, you will likely find it more convenient to create rules for scoring that will be automatically applied to each new entry every time you update Elfeed. You can currently score against title, feed & content by defining strings that will be matched against those attributes by substring, regexp or whole-word match. Rules can be scoped by Elfeed entry tags, so that a rule will only be applied if an entry has certain tags (or does not have certain tags). Each rule defines an integral value, and the rules are applied in order of definition. The new entry's score begins at zero, and is adjusted by the value defined by each matching scoring rule.

For instance, here's a subset of my scoring file at the moment:

#+BEGIN_EXAMPLE
;;; Elfeed score file                                     -*- lisp -*-
(("title"
  ("OPEN THREAD" -1000 S 1576681345.4086394)
  ("raymond c\\(hen\\)?" 250 r 1576808786.1558545) (t .(@dev)))
 ("content"
  ("type erasure" 500 s 1576808786.043517))
 ("title-or-content"
  ("california" 150 100 s 1576808786.4068587)
  ("china" 150 100 w 1576808786.1848788))
 ("feed"
  ("Essays in Idleness" 250 S t 1576808786.1956885)
  ("Irreal" 250 S t 1576808786.1765869)
  ("Julia Evans" 100 s t 1576808786.4092398)
  ("National Weather Service" 400 S t 1576808786.1117532)
  ("emacs-news – sacha chua" 350 S t 1576808785.3807983))
 (mark -2500))
#+END_EXAMPLE

Like Gnus scoring, this may look like Lisp code, but it is not directly eval'd. It will be read by the Lisp reader, so it must at least be a valid Lisp s-expression. You can find details below.

* Prerequisites

This package was developed against [[https://github.com/skeeto/elfeed][Elfeed]] 3.3.0, which itself requires Emacs 24.3 and cURL.

* Installing

The easiest way to install elfeed-score is [[https://github.com/melpa/melpa][MELPA]]; assuming you've got MELPA in your =package-archives=, just say:

#+BEGIN_SRC elisp :tangle yes :comments no
  (use-package elfeed-score
    :ensure t
    :config
    (progn
      (elfeed-score-enable)
      (define-key elfeed-search-mode-map "=" elfeed-score-map)))
#+END_SRC

You can, if you wish, install from source as well:

#+BEGIN_EXAMPLE
cd /tmp
curl -L --output=elfeed-score-0.4.0.tar.gz https://github.com/sp1ff/elfeed-score/archive/0.4.0.tar.gz
tar xvf elfeed-score-0.4.0.tar.gz && cd elfeed-score-0.4.0
./configure
make
make install
#+END_EXAMPLE

** Running the Unit Tests

The unit tests require some macros defined by the [[https://github.com/skeeto/elfeed][Elfeed]] test suite, which is not distributed with the MELPA package. Therefore, you'll need to clone the Elfeed git repo & develop against that:

#+BEGIN_EXAMPLE
cd /tmp
git clone https://github.com/skeeto/elfeed.git
curl -L --output=elfeed-score-0.4.0.tar.gz https://github.com/sp1ff/elfeed-score/archive/0.4.0.tar.gz
tar xvf elfeed-score-0.4.0.tar.gz && cd elfeed-score-0.4.0
export EMACSLOADPATH=/tmp/elfeed-score-0.4.0:/tmp/elfeed/tests:$EMACSLOADPATH
./configure
make
make check
#+END_EXAMPLE

Unless you already use =EMACSLOADPATH=, this likely won't work as written-- you'll need to work out exactly how to tell Emacs to pickup Elfeed from your git repo instead of wherever you've got it installed. If you're running the unit tests, I assume you can get this working.

* Getting Started

** Score File Format

The score file (=~/.emacs.d/elfeed.score= by default) is an Emacs Lisp form that evaluates to an association list. Comments are as per usual. The current format recognizes four keys:

    - "title": the value associated with this is a list of rules matching text against the entry title
    - "content": the value associated with this is a list of rules matching text against the entry content
    - "title-or-content": a list of rules matching against both entry title & content
    - "feed": the value associated with this is a list of rules matching text against the entry feed
    - =mark=: an integer which, if greater than an entry's final score, will result in the entry being marked as read (in other words, if your rules have lowered an entry's scores below this level, don't even display it in the Elfeed search buffer)

Title & content rules are defined by a list of length five:

    1. the match text
    2. the match value: this is an integer specifying the amount by which the entry's score should be adjusted, should the text match
    3. the match type: this may be one of =s=, =S=, =r=, =R=, =w= or =W= for substring match, case-sensitive substring match, regexp match or case-sensitive regexp match, and case-insensitive or case-sensitive whole word match, respectively. Whole word matching just feeds the match text to =word-search-regexp= before doing a regexp search.
    4. the last time this rule matched an entry, in seconds since Unix epoch. This element is optional, need not be supplied by the score file author, and will be automatically kept up-to-date by the package.
    5. tag scoping rules (on which more below); this is optional, and won't be written out when the scoring rules are serialized unless it is non-nil.

So, when first setting up your score file, saying:

#+BEGIN_EXAMPLE
;;; Elfeed score file                                     -*- lisp -*-
(("title"
  ("OPEN THREAD" -1000 S))
 ("content"
  ("california" 100 s nil (t . (@daily @politics)))))
#+END_EXAMPLE

means that you want all entries whose title contains the text "OPEN THREAD" to have its score decreased by 1000, and whose content contains the text "california" to have its score increased by 100, but only if the entry has at lease one of the tags =@daily= or =@politics=. The former match will be case-sensitive, the latter case-insensitive.

I've found myself defining duplicate rules for both title & content, albeit with different values (presuming that a match against title would be more significant than a match against content). To eliminate this, I added a "title-or-content" rule type that mimics the formats above, but permits for different values to be added to the score depending on whether the match is found against the title or the content. For instance

#+BEGIN_EXAMPLE
    ;;; Elfeed score file                                     -*- lisp -*-
    (("title-or-content"
      ("california" 150 100 s nil (t . (@daily @politics)))))
#+END_EXAMPLE

defines a rule that will perform a substring match for "california" against both the entry title and content.  A match found in the title adds 150 to the score, and a match found in the content adds 100.  The rule will only be applied, however,
to entries whose tags contain =@daily=, =@politics= or both.

Scoring against the entry's feed is done similarly, but may be done against either the feed title or the feed URL. This is indicated by adding a new element at index 3 which may be one of =t= or =u= (for title or URL, respectively).

Finally, if you've decided that an entry's score is low enough, you may not even want to see it. In that case, add a rule like:

#+BEGIN_EXAMPLE
(mark N)
#+END_EXAMPLE

when the entry's final score is below =N=, the package will remove the =unread= tag from the entry, marking it as "read".

*** Tag Scoping Rules

Limiting rules by entry tags involves the use of a cons cell of the form:

#+BEGIN_EXAMPLE
(BOOLEAN . (TAG...))
#+END_EXAMPLE

The =car= is a boolean, and the =cdr= is a list of tags.  If the former is =t=, the rule will only be applied if the entry has at least one of the tags listed.  If the boolean value is =nil=, the rule will only apply if the entry has *none* of the tags listed.

** Using elfeed-score

Once your score file is setup, load elfeed-score. 

#+BEGIN_SRC elisp :tangle yes :comments no
(require 'elfeed-score)
#+END_SRC

Just loading the library will *not* modify [[https://gitub.com/skeeto/elfeed][Elfeed]]; you need to explicitly enable the package for that:

#+BEGIN_SRC elisp :tangle yes :comments no
(elfeed-score-enable)
#+END_SRC

This will install the new sort function & new entry hook, as well as read your score file. NB. =elfeed-score-enable= is autoloaded, so if you've installed this package in the usual way, you should be able to just invoke the function & have the package loaded & enabled automatically.

The package defines a keymap, but does not bind it to any key. I like to set it to the === key in =elfeed-search-mode-map=:

#+BEGIN_SRC elisp :tangle yes :comments no
(define-key elfeed-search-mode-map "=" elfeed-score-map)
#+END_SRC

At this point, any _new_ entries will be scored automatically, but the entries already in your database have not yet been scored. Scoring is idempotent (scoring an entry more than once will always result in it having the same score assigned). This means you can load up an Elfeed search, and then, in the Elfeed search buffer (=*elfeed-search*=), score all results with "= v" (=elfeed-score/score-search=). When the command completes, the view will be re-sorted by score. Your score file will also have been updated on disk (to record the last time that each rule matched).  If you want to see the scoring actions as they're happening, set =elfeed-score/debug= to =t=.

You can optionally arrange to have the scores displayed in the search buffer:

#+BEGIN_SRC elisp :tangle yes :comments no
(setq elfeed-search-print-entry-function #'elfeed-score-print-entry)
#+END_SRC

This is not turned on by =elfeed-score-enable=; you will need to set this manually. However, =elfeed-score-unload= will remove it, if it's there.

Finally, you can configure score logging by setting the variable =elfeed-score-log-level=. By default it will be ='warn= (which will produce very little output). Other possible settings are ='debug=, ='info=, and ='error=.  To trouble-shoot a balky rule, type =(setq elfeed-score-log-level 'debug)=, re-score your current view, and switch to buffer =*elfeed-score*=.
* Status and Roadmap

I'm using =elfeed-score= day in & day out for my RSS reading, but this is a preliminary release (the version number, 0.4.0, was chosen to suggest this).

Things I want to do next:

    - support adding tags based on score (e.g. "if the score is greater than _n_, add tag 'foo'")
    - add some kind of feature to age out rules that haven't matched in a long time
    - capture which entries are actually opened & which ones are manually marked read without bothering to read them; see if I can "learn" from that information (something like Gnus Adaptive Scoring)

Bugs, comments, feature requests &c welcome at [[mailto:sp1ff@pobox.com][sp1ff@pobox.com]].
